#!/usr/bin/env python
"""
Generate a complete sample CrewAI tool for testing (without API calls)
Uses pre-built template code
"""

import sys
from pathlib import Path

# Add src to path
sys.path.insert(0, str(Path(__file__).parent / "src"))

from base_classes import ToolSpec, ToolInputParameter
from test_generator import TestFileGenerator
from documentation_generator import DocumentationGenerator
from packaging_generator import PackagingGenerator


def generate_sample_tool():
    """Generate a complete sample tool with all features"""

    # Define the sample tool spec
    spec = ToolSpec(
        name="WebScraperTool",
        display_name="Web Scraper",
        description="Extract and analyze content from web pages using CSS selectors",
        category="web",
        version="1.0.0",
        author="CrewAI Component Factory",
        inputs=[
            ToolInputParameter(
                name="url",
                type="str",
                description="The URL of the web page to scrape",
                required=True,
                examples=["https://example.com", "https://api.example.com/data"]
            ),
            ToolInputParameter(
                name="selector",
                type="Optional[str]",
                description="CSS selector to target specific elements (defaults to body)",
                required=False,
                default_value="body",
                examples=["div.content", "p.description", "h1.title"]
            ),
            ToolInputParameter(
                name="max_results",
                type="Optional[int]",
                description="Maximum number of elements to extract",
                required=False,
                default_value=10,
                examples=["5", "10", "20"]
            ),
            ToolInputParameter(
                name="include_links",
                type="Optional[bool]",
                description="Whether to include hyperlinks in the results",
                required=False,
                default_value=True
            )
        ],
        dependencies=["requests", "beautifulsoup4", "lxml"],
        features=[
            "Extract text content from web pages",
            "Support for CSS selectors",
            "Configurable result limits",
            "Optional link extraction",
            "Robust error handling"
        ]
    )

    # Pre-built tool code (template)
    tool_code = '''"""
Web Scraper Tool for CrewAI
Auto-generated by CrewAI Component Generator
"""

from typing import Type, Optional, Any
from pydantic import BaseModel, Field
from crewai.tools import BaseTool


class WebScraperToolSchema(BaseModel):
    """Input schema for WebScraperTool"""
    url: str = Field(..., description="The URL of the web page to scrape")
    selector: Optional[str] = Field(
        default="body",
        description="CSS selector to target specific elements (defaults to body)"
    )
    max_results: Optional[int] = Field(
        default=10,
        description="Maximum number of elements to extract"
    )
    include_links: Optional[bool] = Field(
        default=True,
        description="Whether to include hyperlinks in the results"
    )


class WebScraperTool(BaseTool):
    """Extract and analyze content from web pages using CSS selectors"""

    name: str = "Web Scraper"
    description: str = "Extract and analyze content from web pages using CSS selectors"
    args_schema: Type[BaseModel] = WebScraperToolSchema

    def _run(
        self,
        url: str,
        selector: Optional[str] = "body",
        max_results: Optional[int] = 10,
        include_links: Optional[bool] = True
    ) -> Any:
        """
        Execute the web scraping operation

        Args:
            url: The URL of the web page to scrape
            selector: CSS selector to target specific elements (defaults to body)
            max_results: Maximum number of elements to extract
            include_links: Whether to include hyperlinks in the results

        Returns:
            Scraped content from the web page
        """
        try:
            import requests
            from bs4 import BeautifulSoup

            # Fetch the web page
            response = requests.get(url, timeout=10)
            response.raise_for_status()

            # Parse HTML
            soup = BeautifulSoup(response.content, 'lxml')

            # Find elements using the selector
            elements = soup.select(selector)

            # Limit results
            if max_results and len(elements) > max_results:
                elements = elements[:max_results]

            # Extract content
            results = []
            for element in elements:
                content = {
                    'text': element.get_text(strip=True)
                }

                if include_links:
                    links = [a.get('href') for a in element.find_all('a', href=True)]
                    if links:
                        content['links'] = links

                results.append(content)

            return {
                'url': url,
                'selector': selector,
                'count': len(results),
                'results': results
            }

        except requests.RequestException as e:
            return {"error": f"Failed to fetch URL: {str(e)}"}
        except Exception as e:
            return {"error": f"Scraping failed: {str(e)}"}
'''

    print("=" * 60)
    print("CrewAI Component Generator - Sample Tool Generation")
    print("=" * 60)
    print(f"\nGenerating: {spec.display_name}")
    print(f"Category: {spec.category}")
    print(f"Version: {spec.version}")
    print(f"Dependencies: {', '.join(spec.dependencies)}")
    print()

    print(f"[OK] Tool code generated ({len(tool_code)} characters)")

    # Generate tests
    print("\nStep 1/4: Generating test suite...")
    test_generator = TestFileGenerator()
    test_code = test_generator.generate_test_file(spec, tool_code)
    print(f"[OK] Generated test file ({len(test_code)} characters)")

    # Generate documentation
    print("\nStep 2/4: Generating documentation...")
    doc_generator = DocumentationGenerator()
    documentation = doc_generator.generate(spec, tool_code)
    markdown_doc = doc_generator.to_markdown(documentation)
    print(f"[OK] Generated documentation ({len(markdown_doc)} characters)")
    print(f"[OK] Usage examples: {len(documentation.usage_examples)}")

    # Generate packaging files
    print("\nStep 3/4: Generating packaging files...")
    packaging_generator = PackagingGenerator()
    packaging = packaging_generator.generate(spec, tool_code)
    print(f"[OK] pyproject.toml: {len(packaging.pyproject_toml)} characters")
    print(f"[OK] setup.py: {len(packaging.setup_py)} characters")
    print(f"[OK] README.md: {len(packaging.readme_md)} characters")

    # Save everything
    print("\nStep 4/4: Saving files...")

    # Create output directory
    output_dir = Path(__file__).parent.parent / "crewai-tool-web-scraper"
    output_dir.mkdir(exist_ok=True)

    # Create package directory
    package_dir = output_dir / "web_scraper_tool"
    package_dir.mkdir(exist_ok=True)

    # Save tool code
    tool_file = package_dir / "web_scraper_tool.py"
    tool_file.write_text(tool_code, encoding="utf-8")
    print(f"[OK] Saved: web_scraper_tool.py")

    # Save __init__.py
    init_file = package_dir / "__init__.py"
    init_file.write_text(
        f'"""Web Scraper Tool for CrewAI"""\n\n'
        f'from .web_scraper_tool import WebScraperTool\n\n'
        f'__all__ = ["WebScraperTool"]\n',
        encoding="utf-8"
    )
    print(f"[OK] Saved: __init__.py")

    # Save py.typed marker
    typed_file = package_dir / "py.typed"
    typed_file.write_text("", encoding="utf-8")

    # Save tests
    tests_dir = output_dir / "tests"
    tests_dir.mkdir(exist_ok=True)

    test_init = tests_dir / "__init__.py"
    test_init.write_text("", encoding="utf-8")

    test_file = tests_dir / "test_web_scraper_tool.py"
    test_file.write_text(test_code, encoding="utf-8")
    print(f"[OK] Saved: test_web_scraper_tool.py")

    # Save documentation
    readme_file = output_dir / "README.md"
    readme_file.write_text(markdown_doc, encoding="utf-8")
    print(f"[OK] Saved: README.md")

    # Save packaging files
    (output_dir / "pyproject.toml").write_text(packaging.pyproject_toml, encoding="utf-8")
    (output_dir / "setup.py").write_text(packaging.setup_py, encoding="utf-8")
    (output_dir / "MANIFEST.in").write_text(packaging.manifest_in, encoding="utf-8")
    (output_dir / "LICENSE").write_text(packaging.license_file, encoding="utf-8")
    print(f"[OK] Saved: pyproject.toml, setup.py, MANIFEST.in, LICENSE")

    # Create example usage file
    example_file = output_dir / "example_usage.py"
    example_file.write_text(
        f'''#!/usr/bin/env python
"""
Example usage of the Web Scraper Tool
"""

from web_scraper_tool import WebScraperTool

def main():
    # Initialize the tool
    tool = WebScraperTool()

    # Basic usage
    print("Example 1: Basic scraping")
    result = tool._run(url="https://example.com")
    print(f"Result: {{result}}")
    print()

    # With optional parameters
    print("Example 2: Using CSS selector")
    result = tool._run(
        url="https://example.com",
        selector="p",
        max_results=5
    )
    print(f"Result: {{result}}")
    print()

    # CrewAI integration example
    print("Example 3: CrewAI Integration")
    print("See README.md for complete CrewAI integration examples")

if __name__ == "__main__":
    main()
''',
        encoding="utf-8"
    )
    print(f"[OK] Saved: example_usage.py")

    # Print summary
    print("\n" + "=" * 60)
    print("[DONE] Sample Tool Generation Complete!")
    print("=" * 60)
    print(f"\nOutput directory: {output_dir}")
    print("\nGenerated files:")
    print("  [PKG] Package Structure:")
    print("     - web_scraper_tool/")
    print("       - __init__.py")
    print("       - web_scraper_tool.py")
    print("       - py.typed")
    print("     - tests/")
    print("       - __init__.py")
    print("       - test_web_scraper_tool.py")
    print("     - pyproject.toml")
    print("     - setup.py")
    print("     - MANIFEST.in")
    print("     - README.md")
    print("     - LICENSE")
    print("     - example_usage.py")
    print("\n[DOCS] Next Steps:")
    print("  1. Install dependencies: pip install requests beautifulsoup4 lxml")
    print("  2. Run tests: pytest ../crewai-tool-web-scraper/tests/ -v")
    print("  3. Try example: python ../crewai-tool-web-scraper/example_usage.py")
    print("  4. Build package: cd ../crewai-tool-web-scraper && python -m build")
    print("  5. Install locally: pip install -e ../crewai-tool-web-scraper/")
    print("\n[RUN] For CrewAI Integration:")
    print("  from web_scraper_tool import WebScraperTool")
    print("  from crewai import Agent")
    print("  agent = Agent(role='Web Specialist', tools=[WebScraperTool()])")
    print()


if __name__ == "__main__":
    generate_sample_tool()
