"""
Automated Test Generator for CrewAI Tools
Generates comprehensive test files for generated tools
"""

from typing import List, Dict, Any
from base_classes import ToolSpec, ToolInputParameter


class TestFileGenerator:
    """Generates pytest test files for generated CrewAI tools"""

    def __init__(self):
        self.test_template = self._load_test_template()

    def _load_test_template(self) -> str:
        """Load the base test template"""
        return '''"""
Auto-generated tests for {tool_name}
Generated by CrewAI Component Generator
"""

import pytest
from typing import Any, Dict
{extra_imports}

# Import the tool
from {module_name} import {class_name}


class Test{class_name}:
    """Test suite for {class_name}"""

    @pytest.fixture
    def tool_instance(self):
        """Create a tool instance for testing"""
        {config_params_init}
        return {class_name}({config_params_args})

    def test_import(self):
        """Test that the tool can be imported"""
        assert {class_name} is not None
        assert hasattr({class_name}, '_run')
        assert hasattr({class_name}, 'args_schema')

    def test_instantiation(self, tool_instance):
        """Test that the tool can be instantiated"""
        assert tool_instance is not None
        assert tool_instance.name == "{display_name}"
        assert tool_instance.description == "{description}"

    def test_args_schema(self, tool_instance):
        """Test that args_schema is properly defined"""
        schema = tool_instance.args_schema
        assert schema is not None

        # Verify schema has expected fields
        schema_fields = schema.model_fields
        {schema_field_checks}

    def test_run_with_valid_inputs(self, tool_instance):
        """Test _run() method with valid inputs"""
        {test_valid_inputs}

        # Call _run with test inputs
        result = tool_instance._run(**test_inputs)

        # Verify result is not None and not an error
        assert result is not None
        if isinstance(result, dict):
            assert "error" not in result or result.get("error") is None

    def test_run_with_missing_required(self, tool_instance):
        """Test _run() raises error with missing required parameters"""
        {test_missing_required}

    def test_run_with_invalid_types(self, tool_instance):
        """Test _run() handles invalid input types gracefully"""
        {test_invalid_types}

    def test_error_handling(self, tool_instance):
        """Test that errors are handled gracefully"""
        # Test with problematic inputs that might cause errors
        {test_error_cases}


# Integration tests
class Test{class_name}Integration:
    """Integration tests for {class_name}"""

    def test_tool_registration(self):
        """Test that tool can be registered with CrewAI"""
        from crewai.tools import BaseTool
        assert issubclass({class_name}, BaseTool)

    def test_pydantic_validation(self):
        """Test Pydantic validation works correctly"""
        {test_pydantic_validation}
'''

    def generate_test_file(self, spec: ToolSpec, tool_code: str) -> str:
        """
        Generate a complete test file for a tool

        Args:
            spec: The ToolSpec used to generate the tool
            tool_code: The generated tool code

        Returns:
            Complete test file content
        """
        # Get normalized parameters
        runtime_params = spec.get_normalized_inputs()
        config_params = spec.get_normalized_config_params()

        # Generate test components
        class_name = spec.name
        module_name = self._to_snake_case(spec.name)
        display_name = spec.display_name
        description = spec.description

        # Extra imports based on parameter types
        extra_imports = self._generate_extra_imports(spec)

        # Config parameter initialization
        config_params_init, config_params_args = self._generate_config_params(config_params)

        # Schema field checks
        schema_field_checks = self._generate_schema_checks(runtime_params)

        # Test input generation
        test_valid_inputs = self._generate_test_inputs(runtime_params)
        test_missing_required = self._generate_missing_required_test(runtime_params)
        test_invalid_types = self._generate_invalid_types_test(runtime_params)
        test_error_cases = self._generate_error_cases(runtime_params)
        test_pydantic_validation = self._generate_pydantic_validation(runtime_params)

        # Fill in template
        test_content = self.test_template.format(
            tool_name=spec.name,
            class_name=class_name,
            module_name=module_name,
            display_name=display_name,
            description=description,
            extra_imports=extra_imports,
            config_params_init=config_params_init,
            config_params_args=config_params_args,
            schema_field_checks=schema_field_checks,
            test_valid_inputs=test_valid_inputs,
            test_missing_required=test_missing_required,
            test_invalid_types=test_invalid_types,
            test_error_cases=test_error_cases,
            test_pydantic_validation=test_pydantic_validation
        )

        return test_content

    def _to_snake_case(self, name: str) -> str:
        """Convert PascalCase to snake_case"""
        import re
        s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
        return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).lower()

    def _generate_extra_imports(self, spec: ToolSpec) -> str:
        """Generate extra imports based on parameter types"""
        imports = spec.get_all_type_imports()
        if imports:
            return f"from typing import {', '.join(imports)}"
        return ""

    def _generate_config_params(self, config_params: List[ToolInputParameter]) -> tuple:
        """Generate config parameter initialization code"""
        if not config_params:
            return "# No config parameters", ""

        init_lines = []
        args = []

        for param in config_params:
            if param.default_value is not None:
                if isinstance(param.default_value, str):
                    init_lines.append(f'{param.name} = "{param.default_value}"')
                else:
                    init_lines.append(f'{param.name} = {param.default_value}')
                args.append(f'{param.name}={param.name}')
            else:
                init_lines.append(f'{param.name} = None')
                args.append(f'{param.name}={param.name}')

        return "\n        ".join(init_lines), ", ".join(args)

    def _generate_schema_checks(self, runtime_params: List[ToolInputParameter]) -> str:
        """Generate schema field validation checks"""
        if not runtime_params:
            return "pass  # No runtime parameters"

        checks = []
        for param in runtime_params:
            checks.append(f'assert "{param.name}" in schema_fields')

        return "\n        ".join(checks)

    def _generate_test_inputs(self, runtime_params: List[ToolInputParameter]) -> str:
        """Generate test input values"""
        if not runtime_params:
            return "test_inputs = {}"

        inputs = []
        for param in runtime_params:
            value = self._get_test_value(param)
            inputs.append(f'"{param.name}": {value}')

        return "test_inputs = {\n            " + ",\n            ".join(inputs) + "\n        }"

    def _get_test_value(self, param: ToolInputParameter) -> str:
        """Get appropriate test value for parameter type"""
        # If there's a default, use it
        if param.default_value is not None and not param.required:
            if isinstance(param.default_value, str):
                return f'"{param.default_value}"'
            return repr(param.default_value)

        # Generate based on type
        type_lower = param.type.lower()

        if 'list[str]' in type_lower:
            return '["test1", "test2"]'
        elif 'list[int]' in type_lower:
            return '[1, 2, 3]'
        elif 'list' in type_lower:
            return '["test"]'
        elif 'dict' in type_lower:
            return '{"key": "value"}'
        elif param.type == 'str':
            return '"test_value"'
        elif param.type == 'int':
            return '42'
        elif param.type == 'float':
            return '3.14'
        elif param.type == 'bool':
            return 'True'
        else:
            return '"test"'

    def _generate_missing_required_test(self, runtime_params: List[ToolInputParameter]) -> str:
        """Generate test for missing required parameters"""
        required_params = [p for p in runtime_params if p.required]

        if not required_params:
            return 'pytest.skip("No required parameters to test")'

        # Test with first required parameter missing
        param = required_params[0]
        inputs = [f'"{p.name}": {self._get_test_value(p)}'
                 for p in runtime_params if p.name != param.name]

        return f'''# Test with missing required parameter: {param.name}
        incomplete_inputs = {{
            {", ".join(inputs)}
        }}

        with pytest.raises(Exception):
            tool_instance._run(**incomplete_inputs)'''

    def _generate_invalid_types_test(self, runtime_params: List[ToolInputParameter]) -> str:
        """Generate test for invalid input types"""
        if not runtime_params:
            return 'pytest.skip("No parameters to test")'

        # Pick first parameter and test with wrong type
        param = runtime_params[0]

        wrong_value = '"invalid"' if param.type != 'str' else '12345'

        inputs = [f'"{p.name}": {self._get_test_value(p)}' for p in runtime_params]
        inputs[0] = f'"{param.name}": {wrong_value}'

        return f'''# Test with invalid type for {param.name}
        invalid_inputs = {{
            {", ".join(inputs)}
        }}

        # Should handle gracefully (may raise or return error dict)
        try:
            result = tool_instance._run(**invalid_inputs)
            # If it doesn't raise, check for error in result
            if isinstance(result, dict):
                pass  # Error might be in result
        except Exception:
            pass  # Type error was raised, which is acceptable'''

    def _generate_error_cases(self, runtime_params: List[ToolInputParameter]) -> str:
        """Generate error handling test cases"""
        return '''# Test with empty/None values where applicable
        try:
            result = tool_instance._run(**{})
            # Should handle gracefully
            assert isinstance(result, (dict, str, list, type(None)))
        except Exception as e:
            # Errors are acceptable for edge cases
            assert str(e)  # Error message should exist'''

    def _generate_pydantic_validation(self, runtime_params: List[ToolInputParameter]) -> str:
        """Generate Pydantic validation tests"""
        if not runtime_params:
            return 'pytest.skip("No parameters to test")'

        param = runtime_params[0]

        return f'''from pydantic import ValidationError
        schema = {param.name.title()}Schema = tool_instance.args_schema

        # Test valid data
        valid_data = {{
            {", ".join(f'"{p.name}": {self._get_test_value(p)}' for p in runtime_params)}
        }}
        instance = schema(**valid_data)
        assert instance is not None'''
